// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFO0kiJbvwzmLpVi6XMAXROQNX3D9d5Ok',
    appId: '1:1082051762387:web:e69d6f78a2156a438e1c26',
    messagingSenderId: '1082051762387',
    projectId: 'currency-rate-calculator-26a3a',
    authDomain: 'currency-rate-calculator-26a3a.firebaseapp.com',
    storageBucket: 'currency-rate-calculator-26a3a.firebasestorage.app',
    measurementId: 'G-BVCQYBXV1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJF7wSg2_CkZUdlYgRJ3kJ9hjpnNzBRk',
    appId: '1:1082051762387:android:4d8a49ce86c7756b8e1c26',
    messagingSenderId: '1082051762387',
    projectId: 'currency-rate-calculator-26a3a',
    storageBucket: 'currency-rate-calculator-26a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_8wBtb1fbQKWkJSduu9Kkh2ey4nUjHw',
    appId: '1:1082051762387:ios:84ec7203cd1ec2ef8e1c26',
    messagingSenderId: '1082051762387',
    projectId: 'currency-rate-calculator-26a3a',
    storageBucket: 'currency-rate-calculator-26a3a.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_8wBtb1fbQKWkJSduu9Kkh2ey4nUjHw',
    appId: '1:1082051762387:ios:84ec7203cd1ec2ef8e1c26',
    messagingSenderId: '1082051762387',
    projectId: 'currency-rate-calculator-26a3a',
    storageBucket: 'currency-rate-calculator-26a3a.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFO0kiJbvwzmLpVi6XMAXROQNX3D9d5Ok',
    appId: '1:1082051762387:web:0aac597d3a5820a08e1c26',
    messagingSenderId: '1082051762387',
    projectId: 'currency-rate-calculator-26a3a',
    authDomain: 'currency-rate-calculator-26a3a.firebaseapp.com',
    storageBucket: 'currency-rate-calculator-26a3a.firebasestorage.app',
    measurementId: 'G-9KT4G6KYWB',
  );
}
